[package]
name = "task_log"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
readme = "README.md"
description = "Task based logging"
documetnation = "https://docs.rs/task_log"

[dependencies]
colorful = "0.2.1"
chrono = "0.4.19"
lazy_static = "1.4.0"

[dev-dependencies]
anyhow = "1.0.55"
