name: build

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            rust:
              - '**.rs'
              - 'Cargo.lock'
              - '.github/workflows/**'
      - if: steps.changes.outputs.rust == 'true'
        run: cargo build
